/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pw.sherlock.UI.agent;

import com.pw.sherlock.utils.CustomTabbedPaneUI_V1;
import com.pw.sherlock.BWCalls.AgentCalls;
import com.pw.sherlock.UI.Home;
import java.awt.Component;
import java.awt.Insets;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.text.DefaultCaret;
import org.json.JSONObject;

/**
 *
 * @author pwankhed
 */
public class AgentMon_BasePane extends javax.swing.JPanel {

	/**
	 * Creates new form agentMonitor
	 */
	public AgentMon_BasePane() {
		initComponents();
		
		recMonExpln.setText("<html>Provide visual representation of agent's<br/> heap memory and CPU Utilization</html>");

		AgeHealthCheckExpln.setText("<html>Send a REST call to agent to check the <br/>connectivity status</html>");
		AgeHealthCheckExpln.setSize(AgeHealthCheckExpln.getPreferredSize());

		ageLogExpln.setText("<html>Display the logback.xml file contents <br/>for BW Agent</html>");
		ageLogExpln.setSize(ageLogExpln.getPreferredSize());

		ageMsgConnExpln.setText("<html>Based on the agent trasport, check the <br/>connectivity with message broker</html>");
		ageMsgConnExpln.setSize(ageMsgConnExpln.getPreferredSize());

		ageTraExpln.setText("<html>Display the BW Agent's TRA file contents</html>");
		ageTraExpln.setSize(ageTraExpln.getPreferredSize());

		UIManager.put("TabbedPane.tabInsets", new Insets(2, 1, 2, 20));
		agentMonTabs.setUI(new CustomTabbedPaneUI_V1());

		agentInfoBrief.setSize(agentInfoBrief.getPreferredSize());
		agentInfoBrief.setText("<html>" + AgentCalls.agentInfoBrief + "</html>");
		AgentCalls.agentInfoBrief = null;

		//Default way of using org.jsonString libs
		agentInfoTextArea.setEditable(false);
		DefaultCaret caret = (DefaultCaret) agentInfoTextArea.getCaret();
		caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
		agentInfoTextArea.getCaret().setVisible(true);
		agentInfoTextArea.getCaret().setSelectionVisible(true);
		JSONObject json = new JSONObject(AgentCalls.agentInfo); // Convert text to object
		agentInfoTextArea.setText(json.toString(4));

		//Freeing up the memory from AgentCalls.agentInfo static string variable, since the data is now available in text area
		AgentCalls.agentInfo = null;

		if ("Yes".equals(Home.master_loadAgentMon)) {
			agentMonSwitch.setSelected(true);
			Component firstAgentChartPane = new AgentMon_ChartsUI();
			Icon agentIcon = new javax.swing.ImageIcon(getClass().getResource("/com/pw/sherlock/resources/sys-monitor-24.png"));
			agentMonTabs.addTab("Agent resource monitor", agentIcon, firstAgentChartPane);
		} else {
			agentMonSwitch.setSelected(false);
		}
	}

	//Belwo method executed when the tab is removed
	@Override
	public void removeNotify() {
		super.removeNotify();
		//System.out.println("The tab is just closed (AgentMonBase_Pane");
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agentMonTabs = new javax.swing.JTabbedPane();
        agentInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        agentInfoTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        agentMonSwitch = new javax.swing.JCheckBox();
        recMonExpln = new javax.swing.JLabel();
        AgeHealthCheckExpln = new javax.swing.JLabel();
        ageLogExpln = new javax.swing.JLabel();
        ageTraExpln = new javax.swing.JLabel();
        agentInfoBrief = new javax.swing.JLabel();
        ageMsgConnExpln = new javax.swing.JLabel();
        agentHealthcheckSwitch = new javax.swing.JCheckBox();
        agentMsgConnSwitch = new javax.swing.JCheckBox();
        agentLogbackSwitch = new javax.swing.JCheckBox();
        agentTraSwitch = new javax.swing.JCheckBox();

        jLabel1.setText("jLabel1");

        agentMonTabs.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        agentMonTabs.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        agentInfoTextArea.setColumns(20);
        agentInfoTextArea.setLineWrap(true);
        agentInfoTextArea.setRows(5);
        agentInfoTextArea.setWrapStyleWord(true);
        agentInfoTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(agentInfoTextArea);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setText("Agent Metadata:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel5.setText("BW Agent Configuration:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setText("Available services on this agent:");

        agentMonSwitch.setText("Resource Monitor");
        agentMonSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentMonSwitchActionPerformed(evt);
            }
        });

        recMonExpln.setText("Loading...");

        AgeHealthCheckExpln.setText("Loading...");

        ageLogExpln.setText("Loading...");

        ageTraExpln.setText("Loading...");

        agentInfoBrief.setText("Loading...");
        agentInfoBrief.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ageMsgConnExpln.setText("Loading...");
        ageMsgConnExpln.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        agentHealthcheckSwitch.setText("Agent Healthcheck");
        agentHealthcheckSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentHealthcheckSwitchActionPerformed(evt);
            }
        });

        agentMsgConnSwitch.setText("Agent Messaging connectivity");
        agentMsgConnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentMsgConnSwitchActionPerformed(evt);
            }
        });

        agentLogbackSwitch.setText("Agent logging configuration");
        agentLogbackSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentLogbackSwitchActionPerformed(evt);
            }
        });

        agentTraSwitch.setText("Agent JVM configuration");
        agentTraSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentTraSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(agentMsgConnSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agentMonSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agentHealthcheckSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agentLogbackSwitch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agentTraSwitch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agentInfoBrief, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageLogExpln)
                                    .addComponent(ageTraExpln)
                                    .addComponent(recMonExpln)
                                    .addComponent(ageMsgConnExpln)
                                    .addComponent(AgeHealthCheckExpln))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentInfoBrief)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agentMonSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recMonExpln)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agentHealthcheckSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgeHealthCheckExpln)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agentMsgConnSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageMsgConnExpln)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agentLogbackSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageLogExpln)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agentTraSwitch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageTraExpln)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout agentInfoLayout = new javax.swing.GroupLayout(agentInfo);
        agentInfo.setLayout(agentInfoLayout);
        agentInfoLayout.setHorizontalGroup(
            agentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agentInfoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))
                .addContainerGap())
        );
        agentInfoLayout.setVerticalGroup(
            agentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(agentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        agentMonTabs.addTab("General Info", new javax.swing.ImageIcon(getClass().getResource("/com/pw/sherlock/resources/info-24.png")), agentInfo); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentMonTabs)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agentMonTabs)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agentMonSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentMonSwitchActionPerformed
		// TODO add your handling code here:
		try {
			if (agentMonSwitch.isSelected()) {
				AgentMon_ChartsUI agentChartPane = new AgentMon_ChartsUI();
				Icon agentIcon = new javax.swing.ImageIcon(getClass().getResource("/com/pw/sherlock/resources/sys-monitor-24.png"));
				agentMonTabs.addTab("Agent resource monitor", agentIcon, agentChartPane);
				agentMonTabs.setSelectedIndex(agentMonTabs.indexOfTab("Agent resource monitor"));
			} else {
				int dialogResult = JOptionPane.showConfirmDialog(null, "Closing the monitoring tab and reopening it later will not show the historic monitoring"
						+ " statistics. Are you sure you want to close this tab?", "Warning", JOptionPane.YES_NO_CANCEL_OPTION);
				if (dialogResult == JOptionPane.YES_OPTION) {
					agentMonTabs.remove(agentMonTabs.indexOfTab("Agent resource monitor"));
				} else {
					agentMonSwitch.setSelected(true);
				}
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }//GEN-LAST:event_agentMonSwitchActionPerformed

    private void agentMsgConnSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentMsgConnSwitchActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_agentMsgConnSwitchActionPerformed

    private void agentLogbackSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentLogbackSwitchActionPerformed
		// TODO add your handling code here:
		try {

			SwingUtilities.invokeLater(new Runnable() {
				@Override
				public void run() {
					if (agentLogbackSwitch.isSelected()) {
						if (Home.master_agentConnMode.equals("Remote Connection")) {
							JOptionPane.showMessageDialog(null, "This function is unavailable in 'Remote Connection' mode. "
									+ "If BW Agent and Sherlock are running on same machine, log in using 'Local Connection' mode and try again", "Connect error", JOptionPane.ERROR_MESSAGE);
							agentLogbackSwitch.setSelected(false);
						} else {
							Component agentLogbackTab = new AgentMon_FileContentsTab("bwagent-logback.xml");
							Icon nodeIcon = new javax.swing.ImageIcon(getClass().getResource("/com/pw/sherlock/resources/logback-xml-file-24.png"));
							agentMonTabs.addTab("Agent Logback", nodeIcon, agentLogbackTab);
							agentMonTabs.setSelectedIndex(agentMonTabs.indexOfTab("Agent Logback"));
						}
					} else {
						agentMonTabs.remove(agentMonTabs.indexOfTab("Agent Logback"));
					}
				}
			});
		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }//GEN-LAST:event_agentLogbackSwitchActionPerformed

    private void agentTraSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentTraSwitchActionPerformed
		try {
			SwingUtilities.invokeLater(new Runnable() {
				@Override
				public void run() {
					if (agentTraSwitch.isSelected()) {
						if (Home.master_agentConnMode.equals("Remote Connection")) {
							JOptionPane.showMessageDialog(null, "This function is unavailable in 'Remote Connection' mode. "
									+ "If BW Agent and Sherlock are running on same machine, log in using 'Local Connection' mode and try again", "Connect error", JOptionPane.ERROR_MESSAGE);
							agentTraSwitch.setSelected(false);
						} else {
							Component agentTraTab = new AgentMon_FileContentsTab("bwagent.tra");
							Icon nodeIcon = new javax.swing.ImageIcon(getClass().getResource("/com/pw/sherlock/resources/properties-24.png"));
							agentMonTabs.addTab("Agent TRA", nodeIcon, agentTraTab);
							agentMonTabs.setSelectedIndex(agentMonTabs.indexOfTab("Agent TRA"));
						}
					} else {
						agentMonTabs.remove(agentMonTabs.indexOfTab("Agent TRA"));
					}
				}
			});
		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }//GEN-LAST:event_agentTraSwitchActionPerformed

    private void agentHealthcheckSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentHealthcheckSwitchActionPerformed
		try {
			SwingUtilities.invokeLater(new Runnable() {
				@Override
				public void run() {
					if (agentHealthcheckSwitch.isSelected()) {
						String jsonString = agentInfoTextArea.getText();
						Home.master_teaAgentPort = jsonString.substring(jsonString.indexOf("bw.agent.tea.agent.port") + 27, jsonString.indexOf("bw.agent.tea.agent.port") + 31);
						Component agentHealthCheckTab = new AgentMon_HealthCheckup();
						Icon nodeIcon = new javax.swing.ImageIcon(getClass().getResource("/com/pw/sherlock/resources/healthCheck-24.png"));
						agentMonTabs.addTab("Agent Healthcheck", nodeIcon, agentHealthCheckTab);
						agentMonTabs.setSelectedIndex(agentMonTabs.indexOfTab("Agent Healthcheck"));
					} else {
						agentMonTabs.remove(agentMonTabs.indexOfTab("Agent Logback"));
					}
				}
			});
		} catch (Exception ex) {
			ex.printStackTrace();
		}
    }//GEN-LAST:event_agentHealthcheckSwitchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeHealthCheckExpln;
    private javax.swing.JLabel ageLogExpln;
    private javax.swing.JLabel ageMsgConnExpln;
    private javax.swing.JLabel ageTraExpln;
    public static javax.swing.JCheckBox agentHealthcheckSwitch;
    private javax.swing.JPanel agentInfo;
    private javax.swing.JLabel agentInfoBrief;
    private javax.swing.JTextArea agentInfoTextArea;
    public static javax.swing.JCheckBox agentLogbackSwitch;
    public static javax.swing.JCheckBox agentMonSwitch;
    private javax.swing.JTabbedPane agentMonTabs;
    public static javax.swing.JCheckBox agentMsgConnSwitch;
    public static javax.swing.JCheckBox agentTraSwitch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel recMonExpln;
    // End of variables declaration//GEN-END:variables
}
