/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pw.sherlock.UI;

import com.pw.sherlock.OshiImpls.OshiMiscFuncs;
import com.pw.sherlock.utils.SherlockUtils;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author pwankhed
 */
public class NodeProps extends javax.swing.JDialog {

	public NodeProps(java.awt.Frame parent, boolean modal, String nodeName, String nodeWorkingDir) {
		super(parent, modal);
		initComponents();
		setTitle("Properties of " + nodeName);
		loadConfigFiles(nodeWorkingDir, nodeName);
	}

	private void loadConfigFiles(String nodeWorkingDir, String nodeName) {
		try {

			OshiMiscFuncs OshiObj = new OshiMiscFuncs();
			String nodeDir = nodeWorkingDir.substring(0, nodeWorkingDir.indexOf("bin"));
			String nodeTra = nodeDir + "bin" + OshiObj.getPathSeparator() + "bwappnode-" + nodeName + ".tra";
			String configIni = nodeDir + "config.ini";
			String nodeLogbackXML = nodeDir + "logback.xml";

			DefaultCaret Tracaret = (DefaultCaret) nodeTraTextArea.getCaret();
			Tracaret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
			nodeTraTextArea.setText(SherlockUtils.readFile(nodeTra));

			DefaultCaret Inicaret = (DefaultCaret) configIniTextArea.getCaret();
			Inicaret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
			configIniTextArea.setText(SherlockUtils.readFile(configIni));

			DefaultCaret logbackCaret = (DefaultCaret) logbackTextArea.getCaret();
			logbackCaret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
			logbackTextArea.setText(SherlockUtils.readFile(nodeLogbackXML));

		} catch (Exception Ex) {
			Ex.printStackTrace();
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodePropsPopUp = new javax.swing.JTabbedPane();
        config_ini = new javax.swing.JPanel();
        configAreaScrollPane = new javax.swing.JScrollPane();
        configIniTextArea = new javax.swing.JTextArea();
        appnode_tra = new javax.swing.JPanel();
        nodeTraScrollPane = new javax.swing.JScrollPane();
        nodeTraTextArea = new javax.swing.JTextArea();
        logback_xml = new javax.swing.JPanel();
        logbackScrollPane = new javax.swing.JScrollPane();
        logbackTextArea = new javax.swing.JTextArea();
        nodPropCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModal(true);
        setName("nodePropsDialog"); // NOI18N
        setResizable(false);

        config_ini.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        configIniTextArea.setEditable(false);
        configIniTextArea.setColumns(20);
        configIniTextArea.setRows(5);
        configAreaScrollPane.setViewportView(configIniTextArea);

        javax.swing.GroupLayout config_iniLayout = new javax.swing.GroupLayout(config_ini);
        config_ini.setLayout(config_iniLayout);
        config_iniLayout.setHorizontalGroup(
            config_iniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(config_iniLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(configAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        config_iniLayout.setVerticalGroup(
            config_iniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(config_iniLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(configAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        nodePropsPopUp.addTab("Functional Configuration", config_ini);

        appnode_tra.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        nodeTraTextArea.setEditable(false);
        nodeTraTextArea.setColumns(20);
        nodeTraTextArea.setRows(5);
        nodeTraScrollPane.setViewportView(nodeTraTextArea);

        javax.swing.GroupLayout appnode_traLayout = new javax.swing.GroupLayout(appnode_tra);
        appnode_tra.setLayout(appnode_traLayout);
        appnode_traLayout.setHorizontalGroup(
            appnode_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appnode_traLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(nodeTraScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        appnode_traLayout.setVerticalGroup(
            appnode_traLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appnode_traLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nodeTraScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        nodePropsPopUp.addTab("JVM Configuration", appnode_tra);

        logback_xml.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        logbackTextArea.setEditable(false);
        logbackTextArea.setColumns(20);
        logbackTextArea.setRows(5);
        logbackScrollPane.setViewportView(logbackTextArea);

        javax.swing.GroupLayout logback_xmlLayout = new javax.swing.GroupLayout(logback_xml);
        logback_xml.setLayout(logback_xmlLayout);
        logback_xmlLayout.setHorizontalGroup(
            logback_xmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logback_xmlLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(logbackScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        logback_xmlLayout.setVerticalGroup(
            logback_xmlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logback_xmlLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(logbackScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        nodePropsPopUp.addTab("Logback Configuration", logback_xml);

        nodPropCloseButton.setText("OK");
        nodPropCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodPropCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(525, Short.MAX_VALUE)
                .addComponent(nodPropCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(nodePropsPopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(608, Short.MAX_VALUE)
                .addComponent(nodPropCloseButton)
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(16, Short.MAX_VALUE)
                    .addComponent(nodePropsPopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nodPropCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodPropCloseButtonActionPerformed
		// TODO add your handling code here:
		dispose();
    }//GEN-LAST:event_nodPropCloseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appnode_tra;
    private javax.swing.JScrollPane configAreaScrollPane;
    private javax.swing.JTextArea configIniTextArea;
    private javax.swing.JPanel config_ini;
    private javax.swing.JScrollPane logbackScrollPane;
    private javax.swing.JTextArea logbackTextArea;
    private javax.swing.JPanel logback_xml;
    private javax.swing.JButton nodPropCloseButton;
    private javax.swing.JTabbedPane nodePropsPopUp;
    private javax.swing.JScrollPane nodeTraScrollPane;
    private javax.swing.JTextArea nodeTraTextArea;
    // End of variables declaration//GEN-END:variables
}
